repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: detect-private-key
    -   id: check-added-large-files
        args: ["--maxkb=2560"]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
    -   id: black
        language_version: python3.12.6
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml", "-r", "."]
        additional_dependencies: ["bandit[toml]"]
        pass_filenames: false
