[project]
name = "bc-python-11-15"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.8.0",
    "pre-commit>=3.8.0",
    "schedule>=1.2.2",
]
